services:
  postgres:
    image: postgres:16
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: permsdb
    ports:
    - "5433:5432"     # externo:interno (evitar choque si corrés varios a la vez)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d permsdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  permissions:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/permsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgres:
          condition: service_healthy
    ports:
      - "8083:8080"